### ISSUE TITLE
immortal supervisor instructions should redirect stderr to a different file

### ISSUE THREAD

**Issue by alexandres** [alexandres/poormanscdn#12]
@nbari : https://github.com/alexandres/poormanscdn#run-as-a-service should redirect to a different file. `stderr` contains important information that will be easy to miss in the large `stdout` output (combined format request logging). 

Also, why does the command specific the log location if it's already in the `run.yml` file?

**Comment by nbari** [comment]
@alexandres the `run.yml` is used by [immortaldir](https://immortal.run/post/immortaldir/) so is persistent across reboots, the [immortal](https://immortal.run/post/immortal/) command will do the same but if you exit your session it will also be terminated.

The command `immortal -l /path/to/log poormanscdn` is just daemonizing `poormanscdn` but will not magically make it persistent across reboots. 

I need to check how to implement `stderr`  https://github.com/immortal/immortal/issues/22 in order to also be automatically rotated and handled like the stderr.

**Comment by alexandres** [comment]
Do you mind if I remove run.yml and the immortal bit from the README until this more mature? I think the lack of stderr will cause confusion. You can then submit a PR when it's ready with perhaps a richer README section for really configuring poormanscdn as a service.

**Comment by nbari** [comment]
definitely, no problem at all was just as an example of how to use, take advantage of the environment vars.

**Comment by nbari** [comment]
Hi, Just in case this has been implemented https://github.com/immortal/immortal/issues/22 in version [0.16.0](https://github.com/immortal/immortal/releases)
