### ISSUE TITLE
Preserve S3 metadata/headers

### ISSUE THREAD

**Issue by bep** [alexandres/poormanscdn#19]
In my tests, it seems like the S3 metadata, which S3 serves as HTTP headers, is lost. This is a big thing, esp. if one have carefully assigned `Cache-Control` values to very static content such as CSS etc.

**Comment by alexandres** [comment]
Cache files are served at https://github.com/alexandres/poormanscdn/blob/master/cache.go#L169 by Http.ServeContent. It is possible to set headers on ResponseWriter before calling Http.ServeContent.

We would have to store the headers in the database under a different namespace. 

Should all metadata be stored and returned when serving cached files?

**Comment by bep** [comment]
>Should all metadata be stored and returned when serving cached files?

I can do some investigating, but I don't see how you can filter it. Also, I realize that I `Gzip` all my content, and without the `Content-Encoding` header, it is not working.

**Comment by bep** [comment]
I can create a suggested PR for this.

**Comment by alexandres** [comment]
> I can do some investigating, but I don't see how you can filter it.

We'll have to cherry pick the headers that we want to preserve. Perhaps a `PreserveHeaders` config option where you specify which headers from S3 should be saved along with the file.

> I can create a suggested PR for this.

That would be great. For the database bit, I would recommend adding a prefix to the keys in  the `database.*File` methods. Then store the metadata using a different prefix for the same path by either 

1. create new methods `database.*Metadata` to store the headers, get, and delete the headers.

or

2. accept the headers as an extra parameter in `database.PutFile` and make sure to delete them in `database.DeleteFile`, and return them in a new method `database.GetMetadata`.

Since headers are small, it seems reasonable to store them as is (couple of lines) and cherry-pick them at runtime in a single pass.

Another thing to consider is that when the server starts it reads the entire cache directory and *adds files to the database if they are not already there*. With metadata, this would have to change to *delete file if they are not in the database*.

**Comment by bep** [comment]
I would prefer that you were a little less specific in your requirements -- this is open source and open source should be fun and interesting; coding by colours is not fun and interesting. I have 15+ years worth of developers experience. I suggest you wait with your comments until you see a PR.

**Comment by alexandres** [comment]
Sorry @bep. I am a little new to this whole process. I've been trying to whiteboard solutions with you to make it easier to contribute, but I might be overdoing it. I will see if I there any resources on open source etiquette so I don't step on anyone's toes.

**Comment by bep** [comment]
Yes, it can be a hard balance. As to this issue; I starting implementing it, but looking at the cache logic, I think I will just create a simpler "static site proxy" that better suits my use case. I guess you still need to fix this header issue for your main use case.

**Comment by alexandres** [comment]
I didn't quite understand the gzip encoding problem. poormanscdn should read the gzip response from S3 and write an uncompressed version to disk. It will then serve a non-gzipped cached version. It should be easy to add gzip support for cached files (something like https://github.com/shurcooL/httpgzip/blob/master/gzip.go ).

I've never had to use Cache-Control either so this hasn't been an issue for me. Go's `http.ServeContent` uses the file's modified times to set the `Last-Modified` header so as to support browser caching but I can see how for static sites you could generate immutable files and benefit from `Cache-Control` for better caching.

Did you run into issues with the implementation?

**Comment by alexandres** [comment]
Both header passthrough and gzip support added in https://github.com/alexandres/poormanscdn/commit/75421a1cf900a285a8a27edf5faf013c14a6fc74
