### ISSUE TITLE
Add TLS support using Let's Encrypt

### ISSUE THREAD

**Issue by bep** [alexandres/poormanscdn#2]
I notice it is on your TODO list, but thought I'd create an issue to raise my hand and say "I will take a stab at implementing it". It is the missing part for this project to be really interesting for my use.

**Comment by alexandres** [comment]
I am would be tremendously thankful if you were to implement it. I should boil down to: 

- Add TLS to https://github.com/alexandres/poormanscdn/blob/master/main.go#L77
- Add Hostname to config.json so Let's Encrypt knows which server to contact
- Add TLSCertificateDir to config.json so Let's Encrypt lib knows where to store the certificate.

Signing libs already maintain the Scheme so they should not have to be changed.

As a sidenote, congratulations on Hugo. One of my go-to tools. Is this the use case you're thinking of for poormanscdn? The advantage of the current cache invalidation scheme is that it eliminates the call to origin so latency is reduced. In this case you would have to pre-sign all links that Hugo generates. Otherwise we will have to add HEAD to origin invalidation.

**Comment by bep** [comment]
>One of my go-to tools. Is this the use case you're thinking of for poormanscdn? 

Indirectly, but it is for me personally. I have a bunch of static sites hosted directly (too many, and very low traffic), and have looked for some kind of easy way to get TLS + CDN + simpler management without adding Cloudfront etc. to the mix. I currently have 1 S3 bucket per site, but I may consolidate this, but I really want 1 config files for all my sites. 

Oh, and once I get this running, of course, it will be interesting to other Hugo users. Kind of like a "poor man's Netlify".

**Comment by alexandres** [comment]
> Not sure what you mean by "query parameters", but I guess I will get to that, eventually... But I guess it should be fixable in any case.

poormanscdn needs to know if it should serve up a file from the cache or get a newer version from S3 (cache invalidation). Presently this is done by the URL query parameter *modified* which specifies the file's last modification time. poormanscdn compares the *modified* time with the timestamp of the file in the cache and serves up the file from cache if its timestamp is newer than *modified*, else it retrieves the newer version from S3.

On the TODO list is HEAD invalidation: in this case poormanscdn would issue a HEAD request to S3 to get the last modified time of a file rather than use the *modified* query parameter. This had two downsides: increased latency and paid requests.

An interesting alternative (which I think is what you have in mind with Netlify) would be to use *purging*: you could make a signed DELETE call to poormanscdn to invalidate a specific file, or have some catch-all option that invalidates the entire cache. You could then add a hook to git that executes this purge whenever there's a commit. This is trivial to implement and sounds quite handy.

**Comment by bep** [comment]
>This is trivial to implement and sounds quite handy.

This was how I intuitively thought this would work, and is what makes most sense for static sites -- i.e. purge entire cache on new deployment. One could _maybe_ add some more fine grained, but the "purgeAll" query param (or something) should solve mine and I guess 99.9 of similar use cases.

**Comment by alexandres** [comment]
> This was how I intuitively thought this would work, and is what makes most sense for static sites -- i.e. purge entire cache on new deployment. So the "purge all or specific file" (or something) should solve mine and I guess 99.9% of similar use cases.

Done and pushed to master! Thank you for the suggestion.

**Comment by bep** [comment]
@alexandres one quick question: Are there some special things to consider getting the S3 access to work? I get some 403 errors I don't really understand. I see this issue about "policy based S3 access" being a problem...? https://github.com/kr/s3/issues/22

**Comment by alexandres** [comment]
Do you have SigRequired set to true in config.json? Set that to false and see if the error persists. Errors should be informative on stderr (todo).
