### ISSUE TITLE
Multisite setup

### ISSUE THREAD

**Issue by bep** [alexandres/poormanscdn#7]
I will wrap up #2 in a day or two. It looks very promising (those Let's Encrypt people have revolutionised SSL) so I thought I would open an issue to discuss one other change needed for this to be really valuable (and I like this more and more when I think about it):

**I need to support many static sites from one instance/config.**

I figure we could add a mapping between domain and "bucket root:

```
site1.com => firstbucket/site1
site2.com => firstbucket/site2
site3.com => secondbucket
```

In the above "firstbucket" is the bucket name and "site1" is the root folder for "site1.com". That way we put many sites into one S3 bucket if needed (simpler management; and it also avoids hitting the upper limit of buckets).

Having one secret etc. for all buckets sounds fine for me.

Also, note that I'm happy to implement the above if we can agree on how it should look.

**Comment by alexandres** [comment]
Perhaps in config.json

```json
"HostBucketMap": {
      "site1.com": { "S3Bucket": "firstbucket", "Path": "site1", "S3AccessKey": "", "S3SecretKey": "" },
      "site2.com": { "S3Bucket": "firstbucket", "Path": "site1", "S3AccessKey": "", "S3SecretKey": "" },
      "site3.com": { "S3Bucket": "secondbucket", "Path": "", "S3AccessKey": "", "S3SecretKey": "" }
} 
```
For Let's Encrypt to work, the host has to be specified so this could be the needed setup for #2. Thus a config file would need at least one mapping. Perhaps have S3 keys default to global if empty?

For the implementation, Cache would need to prefix its paths with S3Bucket/Path/ so that cache dir and db could be shared. handler.go would use the config to prefix this to all paths before calling Cache. 

Each mapping would need its own StorageProvider. I think this is interesting in case we support different providers in the future. Cache calls StorageProvider.Read(path string, w *CacheWriter), thus StorageProvider can simply strip the S3Bucket bucket from the prefix before calling S3.

StorageProvider would need to be injected into Cache for handler.go calls. 

Putting it altogether, something like:

handler.go:
```go
storageProvider := use r.Host to select the correct StorageProvider
prefixedPath := storageProvider.PrefixPath(path)
cacheError := cache.Read(prefixedPath, lastModifiedAtTime, cacheClient, storageProvider)
```

s3.go:
```go
func (c S3Client) PrefixPath(path string) string {
     return c.bucket + "/" + c.path + "/" + path
}

func (c S3Client) buildS3Url(path string) string {
    return path stripped of PrefixPath
}
```

**Comment by bep** [comment]
>Thus a config file would need at least one mapping. Perhaps have S3 keys default to global if empty?


I assume this project is in a "pre 1.0" state, so breaking changes would be OK. I would say that a config schema should be clear and without ambiguity. Having "two ways" to do the same is what you see in legacy software.

I like your suggestion, it seems to be future proof. I suggest naming it `Hosts` instead of `HostBucketMap`, but that is just a detail. I try to work this into my SSL Pull Request.

**Comment by alexandres** [comment]
Definitely pre1. 0. Though I have been using the initial commit version for quite some time without issue, I released to the public only a few days ago. We're definitely free to make breaking changes. 

I agree with Hosts rather than HostBucketMap. 

I forgot to mention that Cache.DeleteAll will need to be changed to Cache.DeleteWithPrefix to avoid purging the entire cache if only a single site changes.

**Comment by alexandres** [comment]
I'm not sure how per host AWS credentials will work with ENV configuration. Seems like it might become a bit messy. 

Do you think we should keep only global credentials? Should they only come from the ENV? Your comment on a single way to do things made me question this design decision.

**Comment by bep** [comment]
My use case would be to set up one S3 policy for all and set the keys in OS env. So, yes, I think that should be 

1) A global setting with OS env support
2) But it should probably also be possible to set it per host.

The logic is a little bit the other way around right now, but I would suggest that:

**Only use the OS env vars if not set on the host.**

**Comment by alexandres** [comment]
I agree. That seems like the way to do it.

We might run into trouble when different storage providers are implemented
and the S3 Host keys (Bucket, S3Secret) no longer make sense.

On Aug 19, 2017 5:32 PM, "Bjørn Erik Pedersen" <notifications@github.com>
wrote:

My use case would be to set up one S3 policy for all and set the keys in OS
env. So, yes, I think that should be

   1. A global setting with OS env support
   2. But it should probably also be possible to set it per host.

The logic is a little bit the other way around right now, but I would
suggest that:

*Only use the OS env vars if not set on the host.*

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/alexandres/poormanscdn/issues/7#issuecomment-323546211>,
or mute the thread

**Comment by bep** [comment]
@alexandres let's see how it works and then adjust. On a side note: What is the "best buy" on cheapish hosts for this with enough geographic spread?

**Comment by alexandres** [comment]
I've been using http://oneprovider.com/ for a couple of years and can recommend them.

**Comment by alexandres** [comment]
I'm closing this as the implementation is complete.

**Comment by alexandres** [comment]
@bep 

I found a bug in the implementation: https://github.com/alexandres/poormanscdn/commit/49d67769c223b24ece0ba0b908ae19b1b66db964#diff-56ffa6659747ba7a23d2b5597a4cda5dL220

The DB calls need to received prefixed paths so as not to conflate cached files from different hosts.

Also made another change: I think it makes more sense to use the hostname as the cache prefix rather than bucket + path. 

Both fixed in https://github.com/alexandres/poormanscdn/commit/49d67769c223b24ece0ba0b908ae19b1b66db964

Let me know what you think.

**Comment by bep** [comment]
@alexandres yes, I scratched my head myself when I started testing this this afternoon. Now it seems to work much better.
